### ISSUE TITLE
Поддержка id-tc26-gost-28147-param-Z (SBOX)

### ISSUE THREAD

**Issue by milabs** [yaruson/GostPlugin#14]
Добавить id-tc26-gost-28147-param-Z (OID 1.2.643.7.1.2.5.1.1) - узел замены, определенный Техническим комитетом по стандартизации "Криптографическая защита информации" (сокращенно - ТК 26) Росстандарта

Этот SBOX стандартизован и войдёт в качестве основного в новые стандарты 34.12-2015 и 34.13-2015

http://infotecs.ru/press/news/18/14508/

**Comment by yaruson** [comment]
Теперь узел замены включён в код, изменения доступны в предварительном релизе 2.0.
Засчитывается?
