### ISSUE TITLE
shipping as a plgx file

### ISSUE THREAD

**Issue by deathtrip** [yaruson/GostPlugin#15]
would it be possible to ship the plugin as a plgx file?
http://keepass.info/help/v2_dev/plg_index.html#plgx

**Comment by yaruson** [comment]
I'm still trying to build a working plgx, but with no success.
As soon as it will be managed, plgx will be shipped alongside with DLL version.
For the meantime you may use DLL, it works both on Windows and Linux/Mono.

**Comment by drizzt** [comment]
It's really easy to release a plgx.
Just start from a "cleaned" git clone:
`git clean -fdx`
And then just execute
`c:\Program Files (x86)\KeePass Password Safe 2\KeePass.exe --plgx-create GostPlugin`
from inside the `GostPlugin/GostPlugin` directory (the directory with `GostPlugin.plgx`)

And now you'll have the `GostPlugin.plgx` file that you can copy on `KeePass.exe` directory and it will be compiled the next time you launch it.

**Comment by yaruson** [comment]
Dears, I've just made `plgx` to compile and load.
Please, check if [this package](https://www.dropbox.com/s/xmsmbdc6d578n32/GostPlugin.plgx?dl=1) will work for you as well.
- MD5 `1cf6c3ada69fa4a337181061d9f0dd07`
- SHA-1 `72b175a4d5a61246e65dd28d7d7d28f0e95f509f`
